// Framework config files to look for
export const FRAMEWORK_CONFIGS = [
  'next.config.js',
  'next.config.mjs',
  'next.config.ts',
  'astro.config.mjs',
  'astro.config.ts',
  'astro.config.js',
  'nuxt.config.js',
  'nuxt.config.ts',
  'remix.config.js',
  'svelte.config.js',
  'angular.json',
  'gatsby-config.js',
  'vue.config.js',
  'wrangler.toml',
  'wrangler.jsonc',
  'vite.config.ts',
  'vite.config.js',
  'webpack.config.js',
  'rollup.config.js',
];

// Common config/manifest files
export const COMMON_FILES = [
  'package.json',
  'tsconfig.json',
  'jsconfig.json',
  '.env.example',
  '.env',
  'docker-compose.yml',
  'Dockerfile',
  'Cargo.toml',
  'go.mod',
  'requirements.txt',
  'pyproject.toml',
  'Gemfile',
  'composer.json',
  'vercel.json',
  'netlify.toml',
  'fly.toml',
  'turbo.json',
  'nx.json',
  'prisma/schema.prisma',
];

// Common directories
export const COMMON_DIRS = [
  'src',
  'app',
  'pages',
  'api',
  'components',
  'lib',
  'public',
  'static',
  'assets',
  'tests',
  'test',
  '__tests__',
  'prisma',
  'supabase',
  'packages',
  'apps',
];
